### ISSUE TITLE
git clone fails

### ISSUE THREAD

**Issue by evanberkowitz** [JeffersonLab/chroma#12]
Recently `git clone --recursive git@github.com:JeffersonLab/chroma.git` has begun failing.

The issue seems to be a missing submodule, `wilsonmg` hosted on @bjoo's bitbucket, which seems to be a private repo.

```
> git clone --recursive git@github.com:JeffersonLab/chroma.git
Cloning into 'chroma'...
Warning: Permanently added the RSA host key for IP address '192.30.253.113' to the list of known hosts.
remote: Counting objects: 74093, done.
remote: Total 74093 (delta 0), reused 0 (delta 0), pack-reused 74093
Receiving objects: 100% (74093/74093), 32.50 MiB | 1.69 MiB/s, done.
Resolving deltas: 100% (59162/59162), done.
Checking connectivity... done.
Submodule 'other_libs/cg-dwf' (git@github.com:JeffersonLab/cg-dwf.git) registered for path 'other_libs/cg-dwf'
Submodule 'other_libs/cpp_wilson_dslash' (git@github.com:JeffersonLab/cpp_wilson_dslash.git) registered for path 'other_libs/cpp_wilson_dslash'
Submodule 'other_libs/qdp-lapack' (git@github.com:JeffersonLab/qdp-lapack.git) registered for path 'other_libs/qdp-lapack'
Submodule 'other_libs/sse_wilson_dslash' (git@github.com:JeffersonLab/sse_wilson_dslash.git) registered for path 'other_libs/sse_wilson_dslash'
Submodule 'other_libs/wilsonmg' (git@bitbucket.org:bjoo/wilsonmg.git) registered for path 'other_libs/wilsonmg'
Cloning into 'other_libs/cg-dwf'...
remote: Counting objects: 276, done.
remote: Total 276 (delta 0), reused 0 (delta 0), pack-reused 276
Receiving objects: 100% (276/276), 1.24 MiB | 773.00 KiB/s, done.
Resolving deltas: 100% (166/166), done.
Checking connectivity... done.
Submodule path 'other_libs/cg-dwf': checked out '7e850581dc552004b2234af78387c174dd35770a'
Cloning into 'other_libs/cpp_wilson_dslash'...
remote: Counting objects: 610, done.
remote: Total 610 (delta 0), reused 0 (delta 0), pack-reused 610
Receiving objects: 100% (610/610), 413.65 KiB | 691.00 KiB/s, done.
Resolving deltas: 100% (439/439), done.
Checking connectivity... done.
Submodule path 'other_libs/cpp_wilson_dslash': checked out '56a4abf64c4d586a73bc2fd7747067f6e92329c9'
Cloning into 'other_libs/qdp-lapack'...
remote: Counting objects: 501, done.
remote: Total 501 (delta 0), reused 0 (delta 0), pack-reused 501
Receiving objects: 100% (501/501), 264.80 KiB | 0 bytes/s, done.
Resolving deltas: 100% (349/349), done.
Checking connectivity... done.
Submodule path 'other_libs/qdp-lapack': checked out 'c1e61d3593b42f39afc68b23752992c88a1e6ef9'
Cloning into 'other_libs/sse_wilson_dslash'...
remote: Counting objects: 888, done.
remote: Total 888 (delta 0), reused 0 (delta 0), pack-reused 888
Receiving objects: 100% (888/888), 482.48 KiB | 384.00 KiB/s, done.
Resolving deltas: 100% (663/663), done.
Checking connectivity... done.
Submodule path 'other_libs/sse_wilson_dslash': checked out 'af5c190b8d63d0129a830a2326a8c30f8ccce4ee'
Cloning into 'other_libs/wilsonmg'...
ssh: connect to host bitbucket.org port 22: Connection refused
fatal: protocol error: bad line length character: f 'git@bitbucket.org:bjoo/wilsonmg.git' into submodule path 'other_libs/wilsonmg' failed
```

**Comment by bjoo** [comment]
Fixed with commit 76882e9426a18b56a0f48acb651ab03000fafc43

**Comment by cpviolator** [comment]
Is there any possibility of changing `git@bitbucket.org:JeffersonLab` to `https://github.com/JeffersonLab` in the `.gitmodules` file? If not, how do I stop my attempts at recursive cloning from failing?

**Comment by bjoo** [comment]
Hi Dean,
I thought I changed this to be protocol agnostic. But maybe only in 'devel'. Which branch are you trying to use. (I recommend 'devel' - for the entire stack...)

Best,
B


Sent from Blue<http://www.bluemail.me/r?b=14874>
On May 15, 2019, at 3:21 PM, Dean Howarth <notifications@github.com<mailto:notifications@github.com>> wrote:

Is there any possibility of changing git@bitbucket.org:JeffersonLab to https://github.com/JeffersonLab in the .gitmodules file? If not, how do I stop my attempts at recursive cloning from failing?

**Comment by cpviolator** [comment]
Ahh, great, thank you Balint. I was actually using a custom Chroma that was forked from master, and when I checked master it was still using ssh. I see that your devel branch is the same as QIO and LIME in that it is protocol agnostic, so we can just change the custom branch similarly.

**Comment by grokqcd** [comment]
Hi Balint,
    What’s stopping us from merging qdp++/chroma devel branches back onto master? This is a bit silly...

Robert


On May 15, 2019, at 4:00 PM, Balint Joo <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Dean,
I thought I changed this to be protocol agnostic. But maybe only in 'devel'. Which branch are you trying to use. (I recommend 'devel' - for the entire stack...)

Best,
B


Sent from Blue<http://www.bluemail.me/r?b=14874>
On May 15, 2019, at 3:21 PM, Dean Howarth <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:

Is there any possibility of changing git@bitbucket.org<mailto:git@bitbucket.org>:JeffersonLab to https://github.com/JeffersonLab in the .gitmodules file? If not, how do I stop my attempts at recursive cloning from failing?

**Comment by bjoo** [comment]
2 things

a) any changes that got made to master rather than devel that can cause a conflict by folks not following the GitFlow model and

b) some degree of human time would be involved testing the merged master. Especially case a) would cause issues  e.g. if a feature was reworked in master by someone and that got overwritten during a merge, resulting in a code that may pass regression tests ( also overwritten by the merge) but the measurement now had a different behavior, which would be discovered later down the line  This is primarily a question of (human) time for the stakeholders involved.

Best,
B

Sent from Blue<http://www.bluemail.me/r?b=14874>
On May 15, 2019, at 11:22 PM, Robert Edwards <notifications@github.com<mailto:notifications@github.com>> wrote:
Hi Balint,
What’s stopping us from merging qdp++/chroma devel branches back onto master? This is a bit silly...

Robert


On May 15, 2019, at 4:00 PM, Balint Joo <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Dean,
I thought I changed this to be protocol agnostic. But maybe only in 'devel'. Which branch are you trying to use. (I recommend 'devel' - for the entire stack...)

Best,
B


Sent from Blue<http://www.bluemail.me/r?b=14874>
On May 15, 2019, at 3:21 PM, Dean Howarth <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:

Is there any possibility of changing git@bitbucket.org<mailto:git@bitbucket.org>:JeffersonLab to https://github.com/JeffersonLab in the .gitmodules file? If not, how do I stop my attempts at recursive cloning from failing?

**Comment by martin-ueding** [comment]
But isn't the `chroma` repository at a point where the `master` is so outdated that everyone just uses the `devel` branch for production anyway?

**Comment by cpviolator** [comment]
May I suggest that @bjoo make the develop branch the default branch? That way, when a user does a simple `git clone https://github.com/JeffersonLab/chroma.git` the develop branch will be the one that is cloned. Furthermore, the develop branch will be the one presented on Chroma's GitHub main page.

**Comment by bjoo** [comment]
Good idea


Sent from Blue<http://www.bluemail.me/r?b=14874>
On May 16, 2019, at 12:01 PM, Dean Howarth <notifications@github.com<mailto:notifications@github.com>> wrote:

May I suggest that @bjoo<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_bjoo&d=DwMCaQ&c=CJqEzB1piLOyyvZjb8YUQw&r=WG01dcOd8ZFLFFNkrpbj6A&m=we8FC8tee7r2MBXygoX75QehfEPFgLD1Msn6QpM4K4I&s=xM0Hww7haETLs7wVI7oFet-1-AGbBgUHbYKnS_jo-N4&e=> make the develop branch the default branch? That way, when a user does a simple git clone https://github.com/JeffersonLab/chroma.git the develop branch will be the one that is cloned. Furthermore, the develop branch will be the one presented on Chroma's GitHub main page.

**Comment by martin-ueding** [comment]
But what is the point of making `devel` the default branch? In that case `devel` really is `master` and there is no git flow with releases going on. If that is the case, one should just merge `devel` into `master` and remove `devel` altogether.
