### ISSUE TITLE
Typo in XML: “WislonFlowGaugeObservables”

### ISSUE THREAD

**Issue by martin-ueding** [JeffersonLab/chroma#17]
The XML output of the Wilson flow has a typo in one of the XML tags: In the file `lib/meas/inline/glue/inline_wilson_flow.cc` it says `MesPlq(xml_out, "WislonFlowGaugeObservables", wf_u);`.

Is that somethat that should be fixed or is it likely that people have written XML parsing scripts that now depend on the name being misspelled?

**Comment by bjoo** [comment]
Hi Martin,
I am not sure if we look at that Tag. It should capture only the plaquettes, which we have elsewhere. 
It would be worth fixing this in ‘devel’.

Thanks, and best wishes, 
 Balint

> On Jan 12, 2017, at 6:21 AM, Martin Ueding <notifications@github.com> wrote:
> 
> The XML output of the Wilson flow has a typo in one of the XML tags: In the file lib/meas/inline/glue/inline_wilson_flow.cc it says MesPlq(xml_out, "WislonFlowGaugeObservables", wf_u);.
> 
> Is that somethat that should be fixed or is it likely that people have written XML parsing scripts that now depend on the name being misspelled?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

--------------------------------------------------------------------------------------
Dr Balint Joo              High Performance Computational Scientist
Jefferson Lab
12000 Jefferson Ave, Suite 3, MS 12B2, Room F217,
Newport News, VA 23606, USA
Tel: +1-757-269-5339,      Fax: +1-757-269-5427
email: bjoo@jlab.org       
-------------------------------------------------------------------------------------

**Comment by martin-ueding** [comment]
I wrote a fix on my `devel`, so this is done.
