### ISSUE TITLE
Note “rossi_basis_v2.tex” cannot be compiled, missing “jnl”

### ISSUE THREAD

**Issue by martin-ueding** [JeffersonLab/chroma#25]
The file `rossi_basis_v2.tex` starts with the following:

```tex
\input jnl
```

That file is not contained in the repository, therefore it cannot be compiled. Could you please add that into the repository and check that the documentation can be build?

**Comment by grokqcd** [comment]
Fixed this particular file. It’s a tex file.

		Robert
