### ISSUE TITLE
Deprecate libraries: CG-DWF SSE_WILSON_DSLASH

### ISSUE THREAD

**Issue by bjoo** [JeffersonLab/chroma#4]
Hi Folks, 
 Should we consider deprecating sse_wilson_dslash and cg-dwf before making this source public? 

CG-DWF is actually not strictly speaking ours, but belongs to MIT, but even they are not really using it anymore.

sse_wilson_dslash has essentially been superceded by cpp_wilson_dslash.

Thoughts?
Best, B

**Comment by martin-ueding** [comment]
Do I understand it correctly that `cpp_wilson_dslash` is somewhat superseded by QPhiX now? At least QPhiX seems to be forked from `cpp_wilson_dslash`.

**Comment by grokqcd** [comment]
The cpp_wilson_dslash is fairly generic and has superseded sse_wilson_dslash. The QPhiX is more specific to the Intel vector architectures. Yes, it forked from cpp_wilson_dslash because it gave a framework for the code devel. of the new code. Upshot, we keep both cpp_wilson_dslash & QPhiX.
