### ISSUE TITLE
Error compiling Chroma ( worked until 3 days ago)

### ISSUE THREAD

**Issue by nicolin** [JeffersonLab/chroma#73]
@bjoo 
/home/dp006/dp006/dc-gove1/QudaBench/FASTSUM/QCDSolvers/chroma/lib/actions/ferm/invert/quda_solvers/syssolver_linop_clover_quda_multigrid_w.cc: In member function ‘Chroma::SystemSolverResults_t Chroma::LinOpSysSolverQUDAMULTIGRIDClover::qudaInvert(Chroma::CloverTermT<QDP::OLattice<QDP::PSpinVector<QDP::PColorVector<QDP::RComplex<QDP::Word<double> >, 3>, 4> >, QDP::OLattice<QDP::PScalar<QDP::PColorMatrix<QDP::RComplex<QDP::Word<double> >, 3> > > >&, Chroma::CloverTermT<QDP::OLattice<QDP::PSpinVector<QDP::PColorVector<QDP::RComplex<QDP::Word<double> >, 3>, 4> >, QDP::OLattice<QDP::PScalar<QDP::PColorMatrix<QDP::RComplex<QDP::Word<double> >, 3> > > >&, const T&, Chroma::LinOpSysSolverQUDAMULTIGRIDClover::T&) const’:
/home/dp006/dp006/dc-gove1/QudaBench/FASTSUM/QCDSolvers/chroma/lib/actions/ferm/invert/quda_solvers/syssolver_linop_clover_quda_multigrid_w.cc:114:32: error: no match for ‘operator=’ (operand types are ‘QDP::Real’ {aka ‘QDP::OScalar<QDP::PScalar<QDP::PScalar<QDP::RScalar<QDP::Word<double> > > > >’} and ‘const double [128]’)
  114 |     ret.resid = quda_inv_param.true_res;

**Comment by eromero-vlc** [comment]
Mmm, that cannot work. That line is assigning double array to a scalar

**Comment by eromero-vlc** [comment]
what branch is this?

**Comment by nicolin** [comment]
devel

PS: I am a RSE at UCL and we are working with partners at NVIDIA and bench-marking QUDA for a UK institute. So in the middle testing NVSHEM builds this popped up ;-) .

**Comment by eromero-vlc** [comment]
QUDA has merged the multiple-right-hand size thing. You may want to try the new branch in chroma [feature/mrhs-mg](https://github.com/JeffersonLab/chroma/tree/feature/mrhs-mg)

**Comment by bjoo** [comment]
Hey there! QUDA’s MRHS interface had to break the way residuals are returned. I have fixed in this in the feature/mrhs-mg branch of Chroma, which is waiting to be merged as a PR (hint hint JLab peeps!). With the MRHS interface they now return an array of residua rather than a single residuum.


Best,
 B


From: nicolin ***@***.***>
Date: Monday, October 14, 2024 at 11:38 AM
To: JeffersonLab/chroma ***@***.***>
Cc: Balint Joo ***@***.***>, Mention ***@***.***>
Subject: Re: [JeffersonLab/chroma] Error compiling Chroma ( worked until 3 days ago) (Issue #73)

devel

PS: I am a RSE at UCL and we are working with partners at NVIDIA and bench-marking QUDA for a UK institute. So in them middle testing NVSHEM builds they popped up ;-) .

Attaching the build script I created that can maybe usefull also.
ChromaBuildQuda.txt<https://github.com/user-attachments/files/17366292/ChromaBuildQuda.txt>

**Comment by nicolin** [comment]
Thanks, I will test on the that branch. The performance we get with NVSHEM is slower that QMP and MPI ( Fastest) on a single node with 4 GPUs so going to have to see what is going on and this fix will help ;-)

**Comment by bjoo** [comment]
Hi @nicolin, are you on the UCL Center for Computational Science Slack?  You can reach me there directly if you like (. If you are going to be working with QUDA and Chroma a lot we can also invite you to the QUDA slack, Best, B


From: nicolin ***@***.***>
Date: Monday, October 14, 2024 at 11:46 AM
To: JeffersonLab/chroma ***@***.***>
Cc: Balint Joo ***@***.***>, Mention ***@***.***>
Subject: Re: [JeffersonLab/chroma] Error compiling Chroma ( worked until 3 days ago) (Issue #73)

Thanks, I will test on the that branch. The performance we get with NVSHEM is slower that QMP and MPI ( Fastest) on a single node with 4 GPUs so going to have to see what is going on and this fix will help ;-)

**Comment by nicolin** [comment]
@bjoo  thanks nice to e-meet you,  yes please invite me to the QUDA slack as I will be working with Kate and Mathius also along with other nvidia contacts.  I am at UCL ARC but have asked about the Center for Computational Science Slack now.

**Comment by nicolin** [comment]
So  feature/mrhs-mg  fixed it .

**Comment by bjoo** [comment]
Hi,
Please send me a non-github email to bjoo AT nvidia.com so I have your email address, and I can invite you to the CUDA slack.
Best wishes,
 Balint


From: nicolin ***@***.***>
Date: Monday, October 14, 2024 at 11:59 AM
To: JeffersonLab/chroma ***@***.***>
Cc: Balint Joo ***@***.***>, Mention ***@***.***>
Subject: Re: [JeffersonLab/chroma] Error compiling Chroma ( worked until 3 days ago) (Issue #73)

@bjoo<https://github.com/bjoo> thanks nice to e-meet you, yes please invite me to the QUDA slack as I will be working with Kate and Mathius also along with other nvidia contacts. I am at UCL ARC but have asked about the Center for Computational Science Slack now.
